export const OPENAI_API_KEY = process.env.NEXT_PUBLIC_OPENAI_API_KEY;
export const TAVILY_API_KEY = process.env.NEXT_PUBLIC_TAVILY_API_KEY;
export const LANGCHAIN_API_KEY = process.env.NEXT_PUBLIC_LANGCHAIN_API_KEY;